homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  customize: !include customize.yaml
  packages: !include_dir_named packages

# introduction:

# Enables the frontend
frontend:
  themes: !include themes.yaml
  javascript_version: latest

# Enables configuration UI
config:

http:
  api_password: !secret apipass
  ssl_certificate: !secret sslcert
  ssl_key: !secret sslkey
  base_url: !secret baseurl
  ip_ban_enabled: True
  login_attempts_threshold: 3
  trusted_networks:
    - 192.168.0.0/24
    - 127.0.0.1
    - 192.168.0.24
    - 192.168.0.75

updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - philips_hue

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time
history:
  exclude:
    domains:
      - camera
      - group
      - sensor
      - sun
      - updater
      - zone
      
recorder:
  db_url: !secret dburl
  purge_interval: 2
  purge_keep_days: 14
  exclude:
    domains:
      - camera
      - group
      - sun
      - updater
      - zone
      
# View all events in a logbook
logbook:
  exclude:
    domains:
      - camera
      - group
      - sensor
      - sun
      - updater
      - zone

logger:
  default: error
  logs:
    requests.packages.urllib3: critical
    homeassistant.components.camera: fatal
    pychromecast.socket_client: critical
    homeassistant.helpers.entity: critical
    homeassistant.components.sensor.nzbget: critical
    homeassistant.components.light.hue: critical
    script: info
    sensor: info

# Track the sun
sun:

map:

influxdb:
  host: 192.168.0.13
  port: 8086
  username: !secret infuser
  password: !secret infpass

google_assistant:
  project_id: !secret google_project
  client_id: !secret google_client
  access_token: !secret google_token
  expose_by_default: false


#Google Calendar
google:
  client_id: !secret googleid
  client_secret: !secret googlesecret

light:
  - platform: hue
    host: 192.168.0.10

mqtt:
  broker: 192.168.0.13
  port: 1883
  username: !secret mqtt2user
  password: !secret mqtt2pass

script: !include_dir_merge_named script/
input_boolean: !include_dir_merge_named input_boolean/
sensor: !include sensors.yaml
tts: !include tts.yaml    
zone: !include zones.yaml
group: !include groups.yaml
automation: !include_dir_merge_list automations/
panel_custom: !include panel_custom.yaml
binary_sensor: !include binary_sensors.yaml