# Sensors..  duh
- platform: spotcrime
  name: Crime Reports
  radius: .01
  days: 7

- platform: rest
  resource: http://192.168.0.13/hass/chores.json
  name: chores_eleanor
  scan_interval: 14400
  value_template: >
    {% set today = now().strftime('%a')  %}
    {% set chores =  value_json.eleanor[ today ] %}
    {{ chores }}

- platform: rest
  resource: http://192.168.0.13/hass/chores.json
  name: chores_lola
  scan_interval: 14400
  value_template: >
    {% set today = now().strftime('%a')  %}
    {% set chores =  value_json.lola[ today ] %}
    {{ chores }}

- platform: rest
  resource: http://192.168.0.13/hass/chores.json
  name: chores_william
  scan_interval: 14400
  value_template: >
    {% set today = now().strftime('%a')  %}
    {% set chores =  value_json.william[ today ] %}
    {{ chores }}

- platform: rest
  resource: http://192.168.0.13/hass/chores.json
  name: responsibilities
  scan_interval: 14400
  value_template: >
    {% set today = now().strftime('%a')  %}
    {% set chores =  value_json.eleanor[ today ] + value_json.lola[ today ] + value_json.william[ today ] %}
    {{ chores }}

- platform: http_room
  device_id: fda50693-a4e2-4fb1-afcf-c6eb07647825
  name: 'William'
  timeout: 5
  away_timeout: 60