# Sensors..  duh
    

- platform: rest
  resource: http://192.168.0.13/hass/chores.json
  name: chores_eleanor
  scan_interval: 14400
  value_template: >
    {% set today = now().strftime('%a')  %}
    {% set chores =  value_json.eleanor[ today ] %}
    {{ chores }}

- platform: rest
  resource: http://192.168.0.13/hass/chores.json
  name: chores_lola
  scan_interval: 14400
  value_template: >
    {% set today = now().strftime('%a')  %}
    {% set chores =  value_json.lola[ today ] %}
    {{ chores }}

- platform: rest
  resource: http://192.168.0.13/hass/chores.json
  name: chores_william
  scan_interval: 14400
  value_template: >
    {% set today = now().strftime('%a')  %}
    {% set chores =  value_json.william[ today ] %}
    {{ chores }}

- platform: rest
  resource: http://192.168.0.13/hass/chores.json
  name: responsibilities
  scan_interval: 14400
  value_template: >
    {% set today = now().strftime('%a')  %}
    {% set chores =  value_json.eleanor[ today ] + value_json.lola[ today ] + value_json.william[ today ] %}
    {{ chores }}

# Glenn's Fitbit  
# - platform: fitbit
#   monitored_resources:
#     - "activities/steps"
#     - "sleep/minutesAsleep"
#     - "devices/battery"

- platform: mqtt_room
  device_id: a445425b_c718_461c_a876_aa647abd99d4
  name: 'Cool device'
  state_topic: 'room_presence'
  timeout: 5
  away_timeout: 60