- alias: Keep Muse GH Alive
  trigger:
    platform: time
    minutes: '/2'
    seconds: 00
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: media_player.muse
        state: 'off'
      - condition: state
        entity_id: media_player.muse
        state: 'idle'
  action:
    service: media_player.play_media
    entity_id: media_player.muse
    data:
      media_content_id: http://192.168.0.13:8123/local/1sec.mp3
      media_content_type: music

- alias: Keep Apollo GH Alive
  trigger:
    platform: time
    minutes: '/2'
    seconds: 00
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: media_player.apollo
        state: 'off'
      - condition: state
        entity_id: media_player.apollo
        state: 'idle'
  action:
    service: media_player.play_media
    entity_id: media_player.apollo
    data:
      media_content_id: http://192.168.0.13:8123/local/1sec.mp3
      media_content_type: music

- alias: Keep Whole House GH Alive
  trigger:
    platform: time
    minutes: '/2'
    seconds: 00
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: media_player.whole_house
        state: 'off'
      - condition: state
        entity_id: media_player.whole_house
        state: 'idle'
  action:
    service: media_player.play_media
    entity_id: media_player.whole_house
    data:
      media_content_id: http://192.168.0.13:8123/local/1sec.mp3
      media_content_type: music