# Voice announcements when the kids arrive and leave various zones

- alias: Kids Arrive at Ally's
  trigger:
    platform: state
    entity_id: 
      - device_tracker.lola_lola
      - device_tracker.eleanor_eleanor
    to: 'allys'
    for: '00:02:00'
  action:
    - service: script.speech_engine
      data_template:
        person_arriving: >
          {% set person = trigger.entity_id.split('.')[1].split('_')[0] %}
          {%- macro greeting_sentence(person) -%}
          {{
          person ~ " has arrived at Allisons house "
          }}
          {%- endmacro -%}
          "{{greeting_sentence(person)}}"
        call_no_announcement: 1

- alias: Kids Leave Ally's
  trigger:
    platform: state
    entity_id: 
      - device_tracker.lola_lola
      - device_tracker.eleanor_eleanor
    from: 'allys'
  action:
    - service: script.speech_engine
      data_template:
        person_arriving: >
          {% set person = trigger.entity_id.split('.')[1].split('_')[0] %}
          {%- macro greeting_sentence(person) -%}
          {{
          person ~ " has left Allisons house "
          }}
          {%- endmacro -%}
          "{{greeting_sentence(person)}}"
        call_no_announcement: 1

- alias: Kids Arrive at GG's
  trigger:
    platform: state
    entity_id: 
      - device_tracker.lola_lola
      - device_tracker.eleanor_eleanor
    to: 'ggs'
    for: '00:02:00'
  action:
    - service: script.speech_engine
      data_template:
        person_arriving: >
          {% set person = trigger.entity_id.split('.')[1].split('_')[0] %}
          {%- macro greeting_sentence(person) -%}
          {{
          person ~ " has arrived at Granny Glyns house "
          }}
          {%- endmacro -%}
          "{{greeting_sentence(person)}}"
        call_no_announcement: 1

- alias: Kids Leave GG's
  trigger:
    platform: state
    entity_id: 
      - device_tracker.lola_lola
      - device_tracker.eleanor_eleanor
    from: 'ggs'
  action:
    - service: script.speech_engine
      data_template:
        person_arriving: >
          {% set person = trigger.entity_id.split('.')[1].split('_')[0] %}
          {%- macro greeting_sentence(person) -%}
          {{
          person ~ " has left Granny Glyns house "
          }}
          {%- endmacro -%}
          "{{greeting_sentence(person)}}"
        call_no_announcement: 1
          
- alias: Kids Arrive at School
  trigger:
    platform: state
    entity_id: 
      - device_tracker.lola_lola
      - device_tracker.eleanor_eleanor
    to: 'sst'
    for: '00:02:00'
  condition:
      condition: time
      after: '06:00:00'
      before: '09:00:00'
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: script.speech_engine
      data_template:
        person_arriving: >
          {% set person = trigger.entity_id.split('.')[1].split('_')[0] %}
          {%- macro greeting_sentence(person) -%}
          {{
          person ~ " has arrived at school "
          }}
          {%- endmacro -%}
          "{{greeting_sentence(person)}}"
        call_no_announcement: 1
          
- alias: Kids Left School
  trigger:
    platform: state
    entity_id: 
      - device_tracker.lola_lola
      - device_tracker.eleanor_eleanor
    from: 'sst'
  condition:
      condition: time
      after: '06:00:00'
      before: '18:00:00'
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: script.speech_engine
      data_template:
        person_arriving: >
          {% set person = trigger.entity_id.split('.')[1].split('_')[0] %}
          {%- macro greeting_sentence(person) -%}
          {{
          person ~ " has left school "
          }}
          {%- endmacro -%}
          "{{greeting_sentence(person)}}"
        call_no_announcement: 1