input_boolean:
  dude_meds:
    name: The Dudes Morning Meds
    initial: off
    icon: mdi:pill

automation:
  - alias: Button Press
    hide_entity: true
    trigger:
      - platform: event
        event_type: dude_meds

    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.dude_meds

  - alias: School Day Check
    trigger:
      - platform: time
        at: '06:45:00'

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.dude_meds
          state: 'off'

        - condition: state
          entity_id: input_boolean.school_mode
          state: 'on'

        - condition: state
          entity_id: binary_sensor.workday_sensor
          state: 'on'

    action:
      - service: input_boolean.turn_on
        entity: input_boolean.alert_mode
        
      - service: script.speech_engine
        data:
          call_dude_meds_school_day: 1

  - alias: Non School Day Check
    trigger:
      - platform: time
        at: '09:15:00'

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.dude_meds
          state: 'off'

        - condition: or
          conditions:
            - condition: state
              entity_id: input_boolean.school_mode
              state: 'off'
            - condition: state
              entity_id: binary_sensor.workday_sensor
              state: 'off'

    action:
      - service: input_boolean.turn_on
        entity: input_boolean.alert_mode

      - service: script.speech_engine
        data:
          call_dude_meds_non_school_day: 1