# Environmental Data inc. Weather, Earthquakes, etc

sensor:
#US Earthquakes
  # - platform: geo_rss_events
  #   name: USGS All Earthquakes
  #   url: https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.atom
  #   categories:
  #     - 'Past Hour'
  #     - 'Past Day'

#Track Moon Phase
  - platform: moon

# Weather Current and Forecast 
  - platform: darksky
    api_key: !secret darksky
    forecast:
      - 1
      - 2
      - 3
    monitored_conditions:
      - temperature
      - apparent_temperature
      - humidity
      - wind_speed
      - cloud_cover
      - precip_probability
      - precip_intensity
      - minutely_summary
      - daily_summary
      - hourly_summary
      - temperature_max
      - temperature_min

  # - platform: crimereports
  #   name: Local Crime
  #   radius: 5000

  - platform: wunderground
    api_key: !secret wunderground
    monitored_conditions:
      - alerts

group:

  weather:
    name: Weather
    view: false
    entities:
      - sensor.dark_sky_temperature
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_daily_high_temperature
      - sensor.dark_sky_daily_low_temperature
      - sensor.dark_sky_cloud_coverage
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_humidity
      - sensor.dark_sky_wind_speed
      - sensor.dark_sky_daily_summary
      - sensor.dark_sky_hourly_summary
      - sensor.dark_sky_minutely_summary
    
  forecast:
    name: Forecast
    entities:
      - sensor.dark_sky_daily_high_temperature_1
      - sensor.dark_sky_daily_low_temperature_1
      - sensor.dark_sky_humidity_1
      - sensor.dark_sky_precip_probability_1
      - sensor.dark_sky_precip_intensity_1
      - sensor.dark_sky_wind_speed_1
      - sensor.dark_sky_cloud_coverage_1
      - sensor.dark_sky_daily_high_temperature_2
      - sensor.dark_sky_daily_low_temperature_2
      - sensor.dark_sky_humidity_2
      - sensor.dark_sky_precip_probability_2
      - sensor.dark_sky_precip_intensity_2
      - sensor.dark_sky_wind_speed_2
      - sensor.dark_sky_cloud_coverage_2
      - sensor.dark_sky_daily_high_temperature_3
      - sensor.dark_sky_daily_low_temperature_3
      - sensor.dark_sky_humidity_3
      - sensor.dark_sky_precip_probability_3
      - sensor.dark_sky_precip_intensity_3
      - sensor.dark_sky_wind_speed_3
      - sensor.dark_sky_cloud_coverage_3

script:  
  notifyonwxalert:
    sequence:
        ## Dismiss any current alert so the UI isn't filled 
        ## up with these if there are more then one.
        ## Only show the latest alert
      - service: persistent_notification.dismiss
        data:
          notification_id: "wxalert"
        ## Create a new persistant notification in the UI for a new alert
      - service_template: >
          {% if states.sensor.pws_alerts.attributes.Message %}
          persistent_notification.create
          {% endif %}
        data_template:
          notification_id: "wxalert"
          message: '{{ states.sensor.pws_alerts.attributes.Message }}'
          title: '{{ states.sensor.pws_alerts.attributes.Description }}'

automation:  
  - alias: 'Wx Alert Notification'
    trigger:
      platform: state
      entity_id: sensor.pws_alerts
    action:
      service: script.notifyonwxalert  

  - alias: TTS and Notify Weather Alert
    trigger:
      platform: state
      entity_id: sensor.pws_alerts
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: '{{states.sensor.pws_alerts.state | int > 0}}'
          ## Added a time condition because I don't want a non-emergency alert waking me up
        - condition: time
          after: '07:00:00'
          before: '22:00:00'
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.alert_mode
      - service: tts.polly
        data_template:
          entity_id:
            - media_player.whole_house
          message: "Heads up. The National Weather Service has issued a 
          {{ states.sensor.pws_alerts.attributes.Description }} for your area, 
          it expires at {{ states.sensor.pws_alerts.attributes.Expires }}."
      ## Do other things! Flash lights or if your TV is on, use Harmony to change 
      ## channels to your preferred news station!
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.alert_mode