# Environmental Data inc. Weather, Earthquakes, etc

sensor:
#US Earthquakes
  - platform: geo_rss_events
    name: USGS All Earthquakes
    url: https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.atom
    categories:
      - 'Past Hour'
      - 'Past Day'

#Track Moon Phase
  - platform: moon

# Weather Current and Forecast 
  - platform: darksky
    api_key: !secret darksky
    forecast:
      - 1
      - 2
      - 3
    monitored_conditions:
      - temperature
      - apparent_temperature
      - humidity
      - wind_speed
      - cloud_cover
      - precip_probability
      - precip_intensity
      - minutely_summary
      - daily_summary
      - hourly_summary
      - temperature_max
      - temperature_min

  - platform: crimereports
    name: Local Crime
    radius: 5000

group:

  weather:
    name: Weather
    view: false
    entities:
      - sensor.dark_sky_temperature
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_daily_high_temperature
      - sensor.dark_sky_daily_low_temperature
      - sensor.dark_sky_cloud_coverage
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_humidity
      - sensor.dark_sky_wind_speed
      - sensor.dark_sky_daily_summary
      - sensor.dark_sky_hourly_summary
      - sensor.dark_sky_minutely_summary
    
  forecast:
    name: Forecast
    entities:
      - sensor.dark_sky_daily_high_temperature_1
      - sensor.dark_sky_daily_low_temperature_1
      - sensor.dark_sky_humidity_1
      - sensor.dark_sky_precip_probability_1
      - sensor.dark_sky_precip_intensity_1
      - sensor.dark_sky_wind_speed_1
      - sensor.dark_sky_cloud_coverage_1
      - sensor.dark_sky_daily_high_temperature_2
      - sensor.dark_sky_daily_low_temperature_2
      - sensor.dark_sky_humidity_2
      - sensor.dark_sky_precip_probability_2
      - sensor.dark_sky_precip_intensity_2
      - sensor.dark_sky_wind_speed_2
      - sensor.dark_sky_cloud_coverage_2
      - sensor.dark_sky_daily_high_temperature_3
      - sensor.dark_sky_daily_low_temperature_3
      - sensor.dark_sky_humidity_3
      - sensor.dark_sky_precip_probability_3
      - sensor.dark_sky_precip_intensity_3
      - sensor.dark_sky_wind_speed_3
      - sensor.dark_sky_cloud_coverage_3