#-------------------------------------------
#  RSS Podcast Alerting function Packages
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
#-------------------------------------------

#-------------------------------------------
feedreader:
    urls:
      - https://hasspodcast.io/feed/podcast
#-------------------------------------------

automation:
  - alias: Send notification of RSS feed title when updated
    initial_state: 'on'
    trigger:
      platform: event
      event_type: feedreader

    action:
      - service: notify.discord
        data_template:
          target: 355533149670998018
          message: "New Podcast available - {{ as_timestamp(now()) | timestamp_custom('%I:%M:%S %p %d %b %Y', true) }}"

      - service: persistent_notification.create
        data_template:
          title: "New HA Podcast available"
          message: "New Podcast available - {{ as_timestamp(now()) | timestamp_custom('%I:%M:%S %p %d%b%Y', true) }}"
          notification_id: "update_available"

      - service: script.tweet_engine
        data_template:
          tweet: >
            "A new Home Assistant Podcast is now available at http://hasspodcast.io"