# Postal Related Packages

homeassistant:
  customize:
    sensor.usps_mail:
      friendly_name: USPS Mail
    sensor.usps_packages:
      friendly_name: USPS Packages
    sensor.fedex:
      icon: mdi:truck-fast

group:
  Mail:
    entities:
      - sensor.usps_mail
      - sensor.usps_packages
      - camera.usps_mail_pictures
      - sensor.fedex
      - sensor.ups

sensor:
  - platform: mqtt
    name: 'USPS Mail'
    state_topic: '/usps/mails'
    value_template: "{{ value }}"

  - platform: mqtt
    name: USPS Packages
    state_topic: '/usps/packages'
    value_template: "{{ value }}"

  #FedEx
  - platform: fedex
    username: !secret fedexuser
    password: !secret fedexpass

  - platform: ups
    username: !secret upsuser
    password: !secret upspass

camera:
  - platform: generic
    name: USPS Mail Pictures
    still_image_url: 'http://192.168.xxx.xxx:8123/local/todays_mails.gif'