# Media Server Package

homeassistant:
  customize:
    sensor.sonarr_commands:
      icon: mdi:apple-keyboard-command
      friendly_name: Commands Running
    sensor.sonarr_queue:
      icon: mdi:view-list
      friendly_name: Items in Queue
    sensor.sonarr_series:
      icon: mdi:format-list-bulleted
      friendly_name: '# of Series Tracked'
    sensor.sonarr_upcoming:
      icon: mdi:alarm-multiple
      friendly_name: Upcoming Shows
    sensor.sonarr_wanted:
      icon: mdi:alert-outline
      friendly_name: Shows Wanted
    sensor.nzbget_uptime:
      icon: mdi:arrow-up-bold
      friendly_name: Uptime
    sensor.nzbget_article_cache:
      icon: mdi:cached
      friendly_name: Articles Cached
    sensor.nzbget_download_rate:
      icon: mdi:download
      friendly_name: Download Rate
    sensor.nzbget_download_size:
      icon: mdi:folder-download
      friendly_name: Dwonload Size
    sensor.nzbget_average_download_rate:
      icon: mdi:download
      friendly_name: Avg. Download Rate
    sensor.radarr_movies:
      icon: mdi:movie-roll
      friendly_name: Movies Tracked
    sensor.radarr_status:
      icon: mdi:radar
      friendly_name: Status
    sensor.radarr_upcoming:
      icon: mdi:alarm-multiple
      friendly_name: Upcoming Movies

media_player:
  - platform: cast
  - platform: plex
    entity_namespace: 'plex'
    include_non_clients: false
    scan_interval: 5
    show_all_controls: false
    use_custom_entity_ids: true
    use_episode_art: true
  - platform: spotify
    client_id: !secret spotifyclient
    client_secret: !secret spotifysecret
  # - platform: firetv
  #   host: 192.168.0.13
  - platform: floorplan_speaker
    name: Boys Panel
  - platform: floorplan_speaker
    name: Girls Panel
  - platform: floorplan_speaker
    name: Entryhall
  # - platform: snapcast
  #   host: 192.168.0.13
  # - platform: mpd
  #   host: 192.168.0.13
    - platform: broadlink
      name: Master Bedroom TV
      host: 192.168.0.14
      mac: '34:EA:34:58:BC:3A'
      ircodes_ini: 'broadlink_media_codes/element.ini'
      ping_host: 192.168.0.18

# Sensors -----------------------------------------------------------------------------

sensor:
  #Plex Media Server      
  - platform: plex
    host: 192.168.0.13
    name: Zeus
    username: !secret plexuser
    password: !secret plexpass

  #Sonarr TV Episode Indexer  
  - platform: sonarr
    api_key: !secret sonarrapi
    host: 192.168.0.13
    port: 8989
    monitored_conditions:
      - series
      - upcoming
      - queue
      - wanted
      - commands
    days: 7

  #Radarr Movie Downloader    
  - platform: radarr
    api_key: !secret radarrapi
    host: 192.168.0.13
    port: 7878
    monitored_conditions:
      - movies
      - upcoming
      - status
    days: 30

  #NZBget 
  - platform: nzbget
    host: 192.168.0.13
    username: nzbget
    password: !secret nzbget
    monitored_variables:
      - uptime
      - average_download_rate
      - download_rate
      - download_size
      - article_cache

  - platform: template
    sensors:
      gorgon_media:
        friendly_name: "Gorgon Media"
        value_template: >-
          {% if is_state('media_player.gorgon', 'playing') %}
            {{states.media_player.gorgon.attributes.app_name}}
          {% else %}
            Stopped
          {% endif %}
      hydra_media:
        friendly_name: "Hydra Media"
        value_template: >-
          {% if is_state('media_player.hydra', 'playing') %}
            {{states.media_player.hydra.attributes.app_name}}
          {% else %}
            Stopped
          {% endif %}
      minotaur_media:
        friendly_name: "Minotaur Media"
        value_template: >-
          {% if is_state('media_player.minotaur', 'playing') %}
            {{states.media_player.minotaur.attributes.app_name}}
          {% else %}
            Stopped
          {% endif %}
      apollo_media:
        friendly_name: "Apollo Media"
        value_template: >-
          {% if is_state('media_player.apollo', 'playing') %}
            {{states.media_player.apollo.attributes.media_title}}
          {% else %}
            Stopped
          {% endif %}
      muse_media:
        friendly_name: "Muse Media"
        value_template: >-
          {% if is_state('media_player.muse', 'playing') %}
            {{states.media_player.muse.attributes.media_title}}
          {% else %}
            Stopped
          {% endif %}
      the_dude_media:
        friendly_name: "The Dude Media"
        value_template: >-
          {% if is_state('media_player.the_dude', 'playing') %}
            {{states.media_player.the_dude.attributes.media_title}}
          {% else %}
            Stopped
          {% endif %}
      emmys__lolas_mini_media:
        friendly_name: "Emmy and Lolas Mini Media"
        value_template: >-
          {% if is_state('media_player.emmys__lolas_mini', 'playing') %}
            {{states.media_player.emmys__lolas_mini.attributes.media_title}}
          {% else %}
            Stopped
          {% endif %}
        
  # - platform: pocketcasts
  #   username: wm.g.morrison@gmail.com
  #   password: stinky1303
  
# Groups ------------------------------------------------------------------------------------

group:
  nzbget:
    name: NZBget
    view: false
    entities:
      - sensor.nzbget_uptime
      - sensor.nzbget_article_cache
      - sensor.nzbget_speed
      - sensor.nzbget_size
      - sensor.nzbget_average_speed
      
  sonarr:
    name: Sonarr
    view: false
    entities:
      - sensor.sonarr_commands
      - sensor.sonarr_queue
      - sensor.sonarr_series
      - sensor.sonarr_upcoming
      - sensor.sonarr_wanted
      
  radarr:
    name: Radarr
    view: false
    entities:
      - sensor.radarr_movies
      - sensor.radarr_status
      - sensor.radarr_upcoming

  mediaplayers: # will be entity_id
    name: Media Players
    view: yes
    entities:
      - media_player.apollo
      - media_player.muse
      - media_player.boys_panel
      - media_player.girls_panel
      - media_player.emmys__lolas_mini
      - media_player.the_dude
      - media_player.whole_house
      - media_player.spotify

