sensor:
  - platform: tautulli
    host: 192.168.0.13:8181
    ssl: false
    verify_ssl: true
    token: 1c66acc034e04fc3a82025c359b37c4d
    monitored_conditions:
      - stream_count
      - stream_count_transcode
      - stream_count_direct_play
      - stream_count_direct_stream
      - total_bandwidth