#-------------------------------------------
#  Clean data for the Floorplan UI.
#-------------------------------------------
homeassistant:
  customize_glob:
    "sensor.floorplan_*":
      emulated_hue_hidden: True
      hidden: True
    "sensor.clock_*":
      emulated_hue_hidden: True
      hidden: True
#---Sensor for Time and Date.-----------------------------
sensor:
  - platform: template
    scan_interval: 30000
    sensors:
      floorplan_date:
        friendly_name: 'Date'
        value_template: >-
          {{now().strftime("%A")}}, {{now().strftime("%B")}} {{now().strftime("%d")}}

  - platform: template
    sensors:
      floorplan_time:
        friendly_name: 'Time'
        value_template: >-
          {{now().strftime("%-I")}}:{{now().strftime("%M")}} {{now().strftime("%p")}}

  - platform: template
    sensors:
      clock_time:
        friendly_name: 'Clock Time'
        value_template: >-
          {{now().strftime("%-I")}}:{{now().strftime("%M")}}

  - platform: template
    scan_interval: 30000
    sensors:
      clock_am_pm:
        friendly_name: 'AM/PM'
        value_template: >-
          {{now().strftime("%p")}}

  - platform: template
    scan_interval: 30000
    sensors:
      clock_day:
        friendly_name: 'Day'
        value_template: >-
          {{now().strftime("%A")}}

  - platform: template
    scan_interval: 30000
    sensors:
      clock_date:
        friendly_name: 'Clock Date'
        value_template: >-
          {{now().strftime("%B")}} {{now().strftime("%d")}} {{now().year}}

  - platform: template
    hide_entity: true
    scan_interval: 30000
    sensors:
      tomorrow:
        friendly_name: 'Tomorrow'
        value_template: >-
          {{ (as_timestamp(now()) + 86400) | timestamp_custom("%a") }}

  - platform: template
    hide_entity: true
    scan_interval: 30000
    sensors:
      day_after_tomorrow:
        friendly_name: 'Day After Tomorrow'
        value_template: >-
          {{ (as_timestamp(now()) + 172800) | timestamp_custom("%a") }}

  - platform: template
    hide_entity: true
    scan_interval: 30000
    sensors:
      day_after_that:
        friendly_name: 'Day After That'
        value_template: >-
          {{ (as_timestamp(now()) + 259200) | timestamp_custom("%a") }}