#-------------------------------------------
#  This is the configuration account for @BearStoneHA - My Home's automated twitter account.
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
#-------------------------------------------
# homeassistant:
#   customize_glob:
#     "input_select.log_*":
#       icon: mdi:bug
#       emulated_hue_hidden: True
#       hidden: False

#Random number - https://www.random.org/integers/?num=1&min=1&max=10&col=1&base=10&format=plain&rnd=new

notify:
  - name: Atomic_HA
    platform: twitter
    consumer_key: !secret twitterconsumerkey
    consumer_secret: !secret twitterconsumersecret
    access_token: !secret twitteraccesstoken
    access_token_secret: !secret twitteraccesssecret

automation:
  - alias: 'New Twitter follower!'
    hide_entity: True
    trigger:
      - platform: event
        event_type: new_follower
    action:
      - service: media_player.play_media
        data_template:
          entity_id:
            - media_player.muse
          media_content_id: "https://raw.githubusercontent.com/CCOSTAN/Home-AssistantConfig/master/sounds/twitter-chirp.mp3"
          media_content_type: audio/mp4

      - service: script.tweet_engine
        data_template:
          tweet: >
            {{ [
            "Hey @{{Value1}}! Enjoy the Journey!",
            "I have a new follower (@{{Value1}}), I just sounded a chirp in the house.",
            "Each new follower like (@{{Value1}}) makes me sound a chirp in the house.",
            "If the AMP (http://amzn.to/2j18dlT) is on & I get a new follower, I sound a chirp! Like (@{{Value1}})!"
            ] | random + "#follome"}}

  - alias: full_moon
    hide_entity: true
    trigger:
      - platform: state
        entity_id: sensor.moon
        to: 'Full Moon'
    action:
      - service: script.tweet_engine
        data_template:
          tweet: >
            {{ [
              "It's a full moon tonight in Old San Antone! Riverwalk anyone?",
              "Wolfbloods Unite!!  It's a Full Moon tonight!! Arrrooooooooooo! (http://www.imdb.com/title/tt2321596/)",
              "There's a Full Moon Risin'! (Yeah, I know it's a bad pun, but HEY!  I'm just a house!)"
            ] | random }}

  - alias: pihole_stats
    # hide_enitity: true
    trigger:
      - platform: time
        at: '23:59:00'
    action:
      - service: script.tweet_engine
        data_template:
          tweet: >
            "Today, I prevented {{states.sensor.pihole_ads_blocked_today.state}} ads from reaching my family via Pi-hole!"

  - alias: spotify_tweet
    trigger:
      - platform: state
        entity_id: media_player.spotify
        to: 'playing'
    action:
      - service: script.tweet_engine
        data_template:
          tweet: >
            "My family is now listening to {{states.media_player.spotify.attributes["media_title"]}} by {{states.media_player.spotify.attributes["media_artist"]}} on Spotify!"


  - alias: 'ISS is above Me -Tweet'

    trigger:
      - platform: state
        entity_id:
          - binary_sensor.iss
        to: 'on'
        from: 'off'

    action:
      - service: script.tweet_engine
        data_template:
          tweet: >
            {{ [
            "The ISS is above me right now!",
            "The International Space Station flys by once a day & that time is NOW! (For me)",
            "I can look up RIGHT NOW and see the ISS.",
            "The International Space Station Rocks! And it's above me RIGHT NOW!"
            ] | random + "#Space"}}
            