#-------------------------------------------
#  This is the configuration account for @BearStoneHA - My Home's automated twitter account.
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
#-------------------------------------------
# homeassistant:
#   customize_glob:
#     "input_select.log_*":
#       icon: mdi:bug
#       emulated_hue_hidden: True
#       hidden: False

#Random number - https://www.random.org/integers/?num=1&min=1&max=10&col=1&base=10&format=plain&rnd=new

notify:
  - name: Atomic_HA
    platform: twitter
    consumer_key: !secret twitterconsumerkey
    consumer_secret: !secret twitterconsumersecret
    access_token: !secret twitteraccesstoken
    access_token_secret: !secret twitteraccesssecret

automation:
  - alias: 'Tweet - New follower!'
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: new_follower
    action:
      - service: media_player.play_media
        data_template:
          entity_id:
            - media_player.muse
          media_content_id: "https://raw.githubusercontent.com/CCOSTAN/Home-AssistantConfig/master/sounds/twitter-chirp.mp3"
          media_content_type: audio/mp4

      - service: script.tweet_engine
        data_template:
          tweet: >-
            {% set handle = trigger.event.data.value1 %}
            {% set location = trigger.event.data.vallue2 %}
            {% set phrases = [
            "Hey " ~ handle ~ "! Thanks for the follow! ",
            "I have a new follower, " ~ handle ~ "! That makes me so happy, I have to CHIRP! ",
            "Wanna know who is super cool? " ~ handle ~ " IS!!! Thanks for making me CHIRP! "
            ] %}
            {% set hashtags = [
              "#FollowMe",
              "#CHIRP, CHIRP"
            ] %}
            {{ phrases|random ~ " " ~ hashtags|random }}

  - alias: 'Tweet - PiHole Stats'
    initial_state: 'on'
    trigger:
      - platform: time
        at: '23:59:00'
    action:
      - service: script.tweet_engine
        data_template:
          tweet: >
            {{ [
            "Today, I prevented {{states.sensor.pihole_ads_blocked_today.state}} ads from reaching my family via Pi-hole!",
            "Today was a good day!  Why, you ask? Because I blocked {{states.sensor.pihole_ads_blocked_today.state}} ads via Pi-Hole!"
            ] | random + " http://www.pi-hole.net"}}

  - alias: 'Tweet - Spotify'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: media_player.spotify
        to: 'playing'
    action:
      - service: script.tweet_engine
        data_template:
          tweet: >-
            {% set title = states.media_player.spotify.attributes["media_title"] %}
            {% set artist = states.media_player.spotify.attributes["media_artist"] %}
            {% set phrases = [
            "My family is now listening to " ~ title ~ " by " ~ artist ~ " on Spotify! ",
            "This house is rockin out to " ~ title ~ " by " ~ artist ~ " on Spotify! ",
            "My family likes Spotify and so do I.  We are now listening to " ~ title ~ " by " ~ artist ~ "! "
            ] %}
            {{phrases|random + "#Spotify" }}

  - alias: 'Tweet - ISS is above Me'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.iss
        to: 'on'
        from: 'off'
    action:
      - service: script.tweet_engine
        data_template:
          tweet: >
            {{ [
            "The International Space Station is above me right now! ",
            "The International Space Station flys by once a day & that time is NOW! (For me) ",
            "I can look up RIGHT NOW and see the International Space Station. ",
            "The International Space Station Rocks! And it's above me RIGHT NOW! "
            ] | random + "#Space " + "#NASA"}}

  - alias: 'Tweet - Full Moon'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.moon
        to: 'Full Moon'
    action:
      - delay: '{{ (range(1, 6)|random|int) }}:{{ (range(1, 50)|random|int) }}:00'
      - service: script.tweet_engine
        data_template:
          tweet: >
            {{ [
              "It's a full moon tonight in Old San Antone! Riverwalk anyone? ",
              "Wolfbloods Unite!!  It's a Full Moon tonight!! Arrrooooooooooo! (http://www.imdb.com/title/tt2321596/) ",
              "There's a Full Moon Risin'! (Yeah, I know it's a bad pun, but HEY!  I'm just a house!) "
            ] | random + "#FullMoon" }}
            
  - alias: 'Tweet - Blog Post'
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: blog

    action:
      - service: script.tweet_engine
        data_template:
          tweet: >-
            {% set title = trigger.event.data.title %}
            {% set url = trigger.event.data.url %}
            {% set phrases = [
            "AtomicPapa just wrote about me on his new blog - " ~ title ~ " - " ~ url ~ " ",
            "I'm so cool, there's a blog post about me! " ~ title ~ " - " ~ url ~ " ",
            "Blogs are awesome.  Especially when the post is about ME! " ~ title ~ " - " ~ url ~ " "
            ] %}
            {{ phrases|random + "#HomeAssistant " + "#blogpost" }}

  - alias: 'Random House stats'
    hide_entity: True
    trigger:
      - platform: time
        hours: '/3'
        minutes: 01
        seconds: 00
    condition:
      - condition: template
        value_template: >
          {%- if states.automation.random_house_stats.attributes.last_triggered -%}
            {{ (as_timestamp(now()) - as_timestamp(states.automation.random_house_stats.attributes.last_triggered)) > 10000 }}
          {%- else -%}
            true
          {%- endif -%}
    action:
      - delay: '0{{ range(0,2) | random | int }}:{{ range(10,59) | random | int }}:00'
      - service: script.tweet_engine
        data_template:
          tweet: >
            {{ [
            "So far, I have prevented {{states.sensor.pihole_ads_blocked_today.state}} ads from hitting the network via Pi-hole! http://www.pi-hole.net",
            "Pi-hole (http://www.pi-hole.net) has serviced {{states.sensor.pihole_dns_queries_today.state}} DNS requests today! #PiHole",
            "There are currently {{states.sensor.pihole_dns_unique_clients.state}} clients connected to #pihole! http://pi-hole.net",
            "Zeus, the server for Home Assistant has been running for {{states.sensor.ha_uptime.state}}",
            "Zeus, the server for Home Assistant is using {{states.sensor.glances_disk_used.state}}% of the hard drive currently.",
            "Today's pollen level here is expected to be {{states.sensor.pollen_level.state}} and the top allergen is {{states.sensor.top_allergen_1.state}} pollen.",
            "I am running Home Assistant version {{states.sensor.current_version.state}}. #homeassistant",
            "Outside is {{states.sensor.dark_sky_temperature.state}}°F and the humidity level is {{states.sensor.dark_sky_humidity.state}}%. Gotta love that Texas #weather!",
            "I know that it will be {{states.sensor.dark_sky_minutely_summary.state}} So I told my family to dress accordingly.",
            "Average internet stats are Download: {{states.sensor.speedtest_download.state}} Mbit/s & Upload {{states.sensor.speedtest_upload.state}} Mbit/s.",
            "The current UV index is {{states.sensor.dark_sky_uv_index.state}} and the Moon is {{states.sensor.moon.state}}.  #Space",
            "Home Assistant has been running for {{states.sensor.uptime.state}} minutes.",
            "My @grandecom internet download speed is about {{states.sensor.speedtest_download.state}} Mbit/s and I am a #cordcutter. @plex",
            "Average Cloud Coverage: {{states.sensor.dark_sky_cloud_coverage.state}}%, Average Temp: {{states.sensor.dark_sky_temperature.state}}°F #Solar (http://www.vmwareinfo.com/2018/01/going-green-to-save-some-green-in-2018.html)"
            ] | random + " #RandomStat"}}