# Automations that run at midnight every day

- alias: Clear Dudes Meds

  trigger:
    platform: time
    at: '00:00:00'

  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.dude_meds