######################################################################
##  Stuff that needs to happen at 06:00am.
######################################################################

- alias: 'Timed 0600'
  trigger:
    - platform: time
      at: '06:00:00'

  condition:
    - condition: state
      entity_id: group.weasley_clock
      state: home
    - condition: state
      entity_id: input_boolean.school_mode
      state: 'on'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri

  action:
    - service: light.turn_on
      entity_id:
        - light.girls
        - light.boy
        - light.lego_lamp
        - light.desk_lamp

    - service: script.tweet_engine
      data_template:
        tweet: >
          {{ [
          "Today is a School day.  I will turn on some lights to get this day started!",
          "Up at the crack of Dawn for School.  We need some lights on.",
          "This is way early.  We need some lights on.",
          "Time to wake up the house with some gentle lighting. (http://amzn.to/2eoQTJy)"
          ] | random + " #Hue"}}
